import {
  type Icon as LucideIcon,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Camera,
  ChevronsUpDown,
  Info,
  LoaderCircle,
  LogOut,
  Minus,
  Monitor,
  Moon,
  Plus,
  SquarePen,
  CircleX,
  Sun,
  Trash,
  SquareSplitVertical,
  Slash,
  GripHorizontal,
  NotebookPen,
  User,
  Mail,
  KeyRound,
} from 'lucide-react';

export type Icon = typeof LucideIcon;

export const Icons = {
  Spinner: LoaderCircle,
  Dropdown: ChevronsUpDown,
  Close: CircleX,
  Alert: AlertCircle,
  Info: Info,
  Left: ArrowLeft,
  Right: ArrowRight,
  Logout: LogOut,
  Minus: Minus,
  Plus: Plus,
  Add: Plus,
  Remove: Trash,
  New: SquarePen,
  SplitY: SquareSplitVertical,
  Divide: Slash,
  Drag: GripHorizontal,
  Note: NotebookPen,
  LightTheme: Sun,
  DarkTheme: Moon,
  SystemTheme: Monitor,
  Camera: Camera,
  Profile: User,
  Email: Mail,
  Password: KeyRound,
};
